Reproducible Research - Peer Assignment 1
========================================================

Reading and Cleaning Data
---------
This code grabs the file and gets rid of incomplete records (i.e. records with any N/A values)

```{r echo=TRUE}
setwd("~/Google Drive/dev/R/coursera/reproducible_research/")
activity_filename <- "./data/activity.csv"
act <- read.csv(activity_filename)
act2 <- act[complete.cases(act),]
act3 <- split(act2, act2$date, drop=TRUE)
head(act2)
```

Daily Mean
------------
This code calculates the mean # of steps taken per day by taking the split data sets and looping over them to sum the steps per day and then append to a list, then take the mean & median of the list


```{r echo=TRUE}
daily_steps <- vector()
for(date in act3){
 daily_steps <- append(daily_steps, as.numeric(sum(date$steps)))
}
myhist <- hist(daily_steps)
daily_mean <- mean(daily_steps)
daily_median <- median(daily_steps)
print(paste("mean steps daily is ", as.character(daily_mean)))
print(paste("median of daily steps is ", as.character(daily_median)))
```
Interval Steps
------------
And now we're apparently plotting the total number of steps across all days by interval:
```{r fig.width=7, fig.height=6}
act4 <- split(act2, act2$interval, drop=TRUE)

interval_steps <- vector()
for(interval in act4){
  interval_steps <- append(interval_steps, sum(interval$steps))
}

plot(interval_steps, type="l")

print(paste("The interval with the most steps is interval #", as.character(which.max(interval_steps))))

```

Inputing Missing Values
-----------------
Calculating the total # of complete cases - the total # of cases:
```{r}
total_count <- length(act$date)
temp <- act[complete.cases(act),]
complete_count <- length(temp$date)
no_of_na <- total_count - complete_count
print(no_of_na)
act5 <- act() # with missing values filled back in 

```




